### PR TITLE
multi-entry: temporarily change docs to singular "module"

### PR DESCRIPTION
**Pull request by KATT**
I spent ten minutes with adding globs and comma-separated paths before giving up going into the issues and searching/finding #175 / #367. 

Maybe delete the `(s)` until the issue is resolved to prevent other people from doing the same. :)

### CODE REVIEW

**Review by agilgur5 — CHANGES_REQUESTED** [review]
Agreed, I fell victim to the same problem then dug into the code and wrote  #367 (which was like my second or third PR as a contributor), hopefully this helps a bit.

The API docs are generated from the `--help` of each subcommand, so you'll need to modify the help text for both `build` and `watch` too:
https://github.com/formium/tsdx/blob/d4c3bb220bba4ab26545b9d1a09ef646f031bc63/src/index.ts#L366

**Comment by KATT** [comment]
Done, I simply used the "edit"-buttons in GitHub, guess you can squash when you merge?

**Review by agilgur5 — APPROVED** [review]
LGTM, thanks for the contribution @KATT . Yep, will squash merge this and edit commit message etc

**Comment by agilgur5** [comment]
@allcontributors please add @KATT for docs

**Pull request merged**
